module.exports = {
    COMMUNITY_CHAT: 'COMMUNITY_CHAT',
    USER_CONNECTED: 'USER_CONNECTED',
    MESSAGE_SENT: 'MESSAGE_SENT',
    USER_DISCONECTED: 'USER_DISCONECTED',
    TYPING: 'TYPING',
    TYPINGOUT: 'TYPINGOUT',
    VERIFY_USER: 'VERIFY_USER',
    LOGOUT: 'LOGOUT',
    PRIVATE_MESS: 'PRIVATE_MESS',
    PRIVATE_USER: 'PRIVATE_USER',
    TYPING_PRIVATE: 'TYPING_PRIVATE'
}